id: P7B4D9442
initial_creation_type: input
source_metadata:
  title: Thirteenth Dalai Lama Series
  language: bo
  description: 'Texts by the Great Thirteenth Dalai Lama Tupten Gyatso (thub bstan
    rgya mtsho, 1876–1933):'
  volume:
    019eed48d001465b9b8d7fe7711e8855:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Sādhanas
    62f2b0bf112f420088b282ed17f6d698:
      title: 'The Tambura of Devotion: A Prayer for the Swift Appearance of the Supreme
        Tulku of the All-Seeing Conqueror and Cardinal Guardian of the Land of Snows'
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:48:11.982624'
last_modified_at: '2022-03-01T01:48:11.982626'
statistics:
  total_words: 834
  total_non_words: 70
quality:
  non_words_ratio: 0.08
